action_id: trunk-single-player-auto-upgrade
date: 2025-05-13 19:48:40
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1747165720
full_timestamp:
  nanos: 141262000
  seconds: 1747165720
trunk_version: 1.22.15
