action_id: trunk-whoami
date: 2025-05-13 19:48:40
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1747165720
full_timestamp:
  nanos: 163987000
  seconds: 1747165720
trunk_version: 1.22.15
